language: python

python: 3.5
sudo: required

env:
  matrix:
    - TEST_TYPE="unit"
#    - TEST_TYPE="e2e"

services:
    - mongodb
    - redis-server

addons:
  apt:
    sources:
    - mongodb-3.0-precise
    - elasticsearch-2.x
    - google-chrome
    packages:
    - mongodb-org-server
    - elasticsearch
    - google-chrome-stable

cache:
    - pip
    - npm

before_install:
    - sudo apt-get purge elasticsearch
    - sudo apt-get install -t stable elasticsearch && sudo service elasticsearch restart
    - nvm install 10
    - nvm use 10
    - npm install -g npm@6
    - node --version
    - export CHROME_BIN=`which google-chrome` && $CHROME_BIN --version
    - chmod a+x ./scripts/*
script:
    - ./scripts/install_run_$TEST_TYPE.sh

after_script:
    - test $TEST_TYPE = "e2e" && killall -9 python

after_success:
    - test $TEST_TYPE = "unit" && coveralls-lcov -v -n coverage/lcov.info > coverage.json && coveralls --merge=coverage.json
